name: Plugin Downloader
description: Download a set of dependencies for minecraft servers with a single command
author: Midka <me@midka.dev>
branding:
  icon: archive
  color: gray-dark

inputs:
  config-file:
    description: Path to the configuration file, default is ./dependencies.json
    required: false
  output-folder:
    description: Path to the output folder where dependencies are downloaded to, default is .
    required: false
  tags:
    description: filter plugins using tags, separated by commas
    required: false
  maven-repository:
    description: the local maven repository path
    required: false
    default: /github/workspace/localM2Repository

runs:
  using: docker
  image: docker://ghcr.io/minehubmc/plugin-downloader:v1.3.3
  args:
    - ${{ inputs.config-file && format('--config {0}', inputs.config-file) }}
    - ${{ inputs.output-folder && format('--out {0}', inputs.output-folder) }}
    - ${{ inputs.tags && format('--tags {0}', inputs.tags) }}
    - ${{ inputs.maven-repository && format('--local-maven-repository {0}', inputs.maven-repository) }}
