name: Plugin Downloader
description: Download a set of dependencies for minecraft servers with a single command
author: Midka <me@midka.dev>
branding:
  icon: archive
  color: gray-dark

inputs:
  config-file:
    description: Path to the configuration file, default is ./dependencies.json
    required: false
  output-folder:
    description: Path to the output folder where dependencies are downloaded to, default is .
    required: false

runs:
  using: docker
  image: ghcr.io/minehubmc/plugin-downloader:latest
  args:
    - ${{ inputs.config-file && format('--config {0}', inputs.config-file) }}
    - ${{ inputs.output-folder && format('--out {0}', inputs.output-folder) }}
